# Generated by Django 3.1.7 on 2021-04-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210402_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
