# Generated by Django 3.1.7 on 2021-04-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_ingredient_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcals',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugars',
            field=models.FloatField(),
        ),
    ]
